#ifndef INC_P2TokenTypes_hpp_
#define INC_P2TokenTypes_hpp_

/* $ANTLR 2.7.7 (2006-11-01): "CayugaQL.g" -> "P2TokenTypes.hpp"$ */

#ifndef CUSTOM_API
# define CUSTOM_API
#endif

#ifdef __cplusplus
struct CUSTOM_API P2TokenTypes {
#endif
	enum {
		EOF_ = 1,
		QUERY = 4,
		RESULT_CLAUSE = 5,
		SELECT_CLAUSE = 6,
		TERM_EXPR = 7,
		STREAM_EXPR = 8,
		WINDOW_CLAUSE = 9,
		STREAM_NAME = 10,
		UNARY_EXPR = 11,
		UNARY_OPS = 12,
		FILTER_EXPR = 13,
		SEQ_OP = 14,
		MU_OP = 15,
		PRED_WINDOW = 16,
		PRED_EXPR = 17,
		AND_EXPR = 18,
		ATOM_PRED = 19,
		DUR_PRED = 20,
		PLUS_MINUS_EXPR = 21,
		MUL_DIV_EXPR = 22,
		EXP_MOD_EXPR = 23,
		CONST_LIT_EXPR = 24,
		ATTR_EXPR = 25,
		ATTR_NAME = 26,
		STREAM_ATTR_NAME = 27,
		FUNC_EXPR = 28,
		COMMA = 29,
		STRING = 30,
		OPEN_CUR_PAREN = 31,
		CLOSE_CUR_PAREN = 32,
		LITERAL_TIME = 33,
		LITERAL_time = 34,
		LITERAL_COUNT = 35,
		LITERAL_count = 36,
		LITERAL_window = 37,
		LITERAL_WINDOW = 38,
		OPEN_PAREN = 39,
		CLOSE_PAREN = 40,
		LITERAL_temporal = 41,
		LITERAL_TEMPORAL = 42,
		LITERAL_predwindow = 43,
		LITERAL_PREDWINDOW = 44,
		COMP_OP = 45,
		PLUS = 46,
		MINUS = 47,
		MUL = 48,
		DIV = 49,
		EXP = 50,
		MOD = 51,
		ATTR_VAR_MARKER = 52,
		DOT = 53,
		QUOTED_STRING = 54,
		INT = 55,
		FLOAT = 56,
		LITERAL_PUBLISH = 57,
		LITERAL_publish = 58,
		LITERAL_UNION = 59,
		LITERAL_union = 60,
		LITERAL_SELECT = 61,
		LITERAL_select = 62,
		LITERAL_AS = 63,
		LITERAL_as = 64,
		LITERAL_FROM = 65,
		LITERAL_from = 66,
		LITERAL_NEXT = 67,
		LITERAL_next = 68,
		LITERAL_FOLD = 69,
		LITERAL_fold = 70,
		LITERAL_FILTER = 71,
		LITERAL_filter = 72,
		LITERAL_AND = 73,
		LITERAL_and = 74,
		LITERAL_OR = 75,
		LITERAL_or = 76,
		LITERAL_NOT = 77,
		LITERAL_not = 78,
		LITERAL_DUR = 79,
		LITERAL_dur = 80,
		LITERAL_YEAR = 81,
		LITERAL_year = 82,
		LITERAL_MONTH = 83,
		LITERAL_month = 84,
		LITERAL_DAY = 85,
		LITERAL_day = 86,
		LITERAL_HOUR = 87,
		LITERAL_hour = 88,
		LITERAL_MIN = 89,
		LITERAL_min = 90,
		LITERAL_SEC = 91,
		LITERAL_sec = 92,
		LE = 93,
		OP_LT = 94,
		GE = 95,
		GT = 96,
		EQ = 97,
		NE = 98,
		LETTER = 99,
		DIGIT = 100,
		INT_FLOAT = 101,
		Exponent = 102,
		NEWLINE = 103,
		WS = 104,
		NULL_TREE_LOOKAHEAD = 3
	};
#ifdef __cplusplus
};
#endif
#endif /*INC_P2TokenTypes_hpp_*/
