/**
 * @file Sender.h
 * @date April 14, 2007
 * @brief The file declares the interface for sender.
 * @author Mingsheng Hong (mshong@cs.cornell.edu)
 */

#ifndef _SENDER_H
#define _SENDER_H

#include <string>
using std::string;

namespace Cayuga {
namespace Sender {
/**
 * @brief A Sender object sends data generated by Cayuga engine asynchronously.
 * @author Mingsheng Hong (mshong@cs.cornell.edu)
 * @date April 14, 2007
 * @version 1.0
 */
class Sender {
public:
	virtual ~Sender() {
	}

	/**
	* @brief Send the input stream asynchronously.
	* @param str The input string to send out
	* @author Mingsheng Hong (mshong@cs.cornell.edu)
	* @date April 14, 2007
	* @version 1.0
	*/
	virtual void send(const string* str) = 0;
private:
}; //class Sender
}  //namespace Receiver
}  //namespace Cayuga

#endif //_SENDER_H
